from ex0.concrete_factories import FlameFactory, AquaFactory

print("Testing Factory")
flame_factory = FlameFactory()
aqua_factory = AquaFactory()
flame_base = flame_factory.create_base()
flame_envolved = flame_factory.create_evolved()
aqua_base = aqua_factory.create_base()
aqua_envolved = aqua_factory.create_evolved()
print(flame_base.describe())
print(flame_base.attack())
print(flame_envolved.describe())
print(flame_envolved.attack())
print()
print("Testing Factory")
print(aqua_base.describe())
print(aqua_base.attack())
print(aqua_envolved.describe())
print(aqua_envolved.attack())
print()
print("Testing battle")
print(flame_base.describe())
print("vs.")
print(aqua_base.describe())
print(" fight!")
print(flame_base.attack())
print(aqua_base.attack())
